### ISSUE TITLE
Incorrect container tag

### ISSUE THREAD

**Issue by hmhka** [BurendoUK/burendo-aws-labs#17]
Push `:latest` tag or update documentation to use tag `:test`

`docker run -it -v $PWD:/labs --platform=linux/amd64 burendouk/aws-labs-cli:latest`
`docker run -it -v $PWD:/labs --platform=linux/amd64 burendouk/aws-labs-cli:test`

* [burendouk/aws-labs-cli/tags](https://hub.docker.com/r/burendouk/aws-labs-cli/tags)

OS container lab documentation [BurendoUK/burendo-aws-labs/Labs/LABS-CONTAINER.md](https://github.com/BurendoUK/burendo-aws-labs/blob/dd16d8ad56f0745a06bc7d35202f22ca29668483/Labs/LABS-CONTAINER.md?plain=1#L21)

**Comment by connoravo** [comment]
Resolved - pipeline failed to push to :latest
